stages: # List of stages for jobs, and their order of execution
  - test
  - all
  - code
  - infrastructure
  - data
image: alzdns.azurecr.io/azd-deploy:latest

# include:
#   - template: Security/SAST.gitlab-ci.yml
#     rules:
#       - if: $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event"

#   - template: Security/Secret-Detection.gitlab-ci.yml
#     rules:
#       - if: $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event"

#   - template: Security/Dependency-Scanning.gitlab-ci.yml
#     rules:
#       - if: $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event"

default:
  before_script:
    - az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
    - azd auth login --client-id $AZURE_CLIENT_ID --client-secret $AZURE_CLIENT_SECRET --tenant-id $AZURE_TENANT_ID
  after_script:
    - az logout
    - azd auth logout
  tags:
    - azure-dev01-docker

all-job:  
  stage: all
  script:
    - bash ./deploy/setup_env.sh
    - azd up
    - bash ./deploy/set_env.sh
  when: manual

code-job:  
  stage: code
  script:
    - bash ./deploy/setup_env.sh
    - azd deploy
  when: manual

infrastructure-job:
  stage: infrastructure   
  script:
    - bash ./deploy/setup_env.sh
    - azd provision
    - bash ./deploy/set_env.sh
  when: manual

data-job:
  stage: data  
  script:
    - bash ./deploy/setup_env.sh
    - bash ./deploy/setup_data.sh
    - ./scripts/prepdocs.sh
  when: manual
