### list of stages, starting with test, then auto_start, each relevant stage and stop
stages: 
  - test
  - auto_start
  - all
  - app
  - infra
  - data
  - auto_stop


### declare image to use in all stages, using mtr azd-deploy from azure team
image: mtr.devops.telekom.de/ccoe_azure/azd-deploy


### declare private runner name to use in relevant stages (can be parameterized in a todo)
variables: 
  DEFAULT_RUNNER: otc_run_docker_m  


### include gitlab scanning

include:
  - template: Security/SAST.gitlab-ci.yml
    rules:
      - if: $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event"

  - template: Security/Secret-Detection.gitlab-ci.yml
    rules:
      - if: $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event"

  - template: Security/Dependency-Scanning.gitlab-ci.yml
    rules:
      - if: $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event"


### auth setup for each step to login and logout before and after
.auth_template: &auth
  before_script:
    - az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
    - azd auth login --client-id $AZURE_CLIENT_ID --client-secret $AZURE_CLIENT_SECRET --tenant-id $AZURE_TENANT_ID
    - az account set --subscription $SUBSCRIPTION_ID
  after_script:
    - az logout
    - azd auth logout

### private runner setup (start and stop runner before each task via templates)
.runner_start_template: &runner_start
  <<: *auth
  script: 
    - |-
      if [ "$DEV_ENV" == "true" ]; then
        echo "skip vm startup"
      else
        echo "start private runner"
        az vm start -g $RUNNER_RG -n $RUNNER_NAME
      fi
  allow_failure: false
  tags:
    - $DEFAULT_RUNNER
  

.runner_stop_template: &runner_stop
  <<: *auth
  script: 
    - |-
      if [ "$DEV_ENV" == "true" ] | [ "$NO_RUNNER_STOP" == "true" ]; then
          echo "skip vm stop"
      else
        echo "deallocate private runner"
        az vm deallocate --name $RUNNER_NAME --resource-group $RUNNER_RG
      fi
  tags:
    - $DEFAULT_RUNNER


### all start jobs in automatic_start stage, that will trigger each relevant stage and start the vm before running the job

all_start:
  stage: auto_start
  <<: *runner_start
  allow_failure: false 
  when: manual

app_start:
  stage: auto_start
  <<: *runner_start
  allow_failure: false 
  when: manual

infra_start:
  stage: auto_start
  <<: *runner_start
  allow_failure: false 
  when: manual

data_start:
  stage: auto_start
  <<: *runner_start
  allow_failure: false 
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger"'
    - if: '$CI_PIPELINE_SOURCE != "trigger"'
      when: manual


### execution of the tasks in their own stage to be able to extend it in case needed
### they each will only run after specified start job in automatic_start

all_task:  
  stage: all
  needs: 
    - all_start
  <<: *auth
  script:
    - bash ./deploy/setup_env.sh
    - azd up
    - azd env get-values
    - bash ./deploy/set_env.sh
  artifacts:
    paths:
      - .ENVIRONMENT
  tags:
    - $RUNNER_TAG
  
app_task:  
  stage: app
  needs: 
    - app_start
  <<: *auth
  script:
    - bash ./deploy/setup_env.sh
    - azd deploy
  tags:
    - $RUNNER_TAG

infra_task:
  stage: infra
  needs: 
    - infra_start
  <<: *auth 
  script:
    - bash ./deploy/setup_env.sh
    - azd provision
    - bash ./deploy/set_env.sh
  artifacts:
    paths:
      - .ENVIRONMENT
  tags: 
    - $RUNNER_TAG

data_task:
  stage: data
  needs: 
    - data_start
  <<: *auth
  script:
    - bash ./deploy/setup_env.sh
    - bash ./deploy/setup_data.sh
  allow_failure: false 
  tags: 
    - $RUNNER_TAG


### all stop jobs in automatic_stop stage, that will trigger after each relevant stage and stop the runner vm

all_terminate:
  stage: all
  <<: *runner_stop
  needs: 
    - all_start
    - all_task

app_terminate:
  stage: app
  <<: *runner_stop
  needs: 
    - app_start
    - app_task

infra_terminate:
  stage: infra
  <<: *runner_stop
  needs: 
    - infra_start
    - infra_task

data_terminate:
  stage: data
  <<: *runner_stop
  needs: 
    - data_start
    - data_task